# Generated by Django 4.2 on 2023-04-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_type', models.CharField(choices=[('BMS Project', 'BMS Project'), ('ELV Project', 'ELV Project'), ('Lighting Fixture', 'Lighting Fixture'), ('Design Project', 'Design Project')], default='BMS Project', max_length=35, verbose_name='Project Type')),
                ('company_name', models.CharField(max_length=200)),
                ('project_start', models.DateField()),
                ('project_finished', models.DateField()),
                ('project_location', models.CharField(max_length=100)),
                ('project_status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=35, verbose_name='Status')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSotware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=200)),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.CharField(max_length=200)),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
